#!/usr/bin/env node
// brandboard: turn .design/brand.json into a brand board you can judge in one image, plus shippable assets.
//
//   node brandboard.mjs [.design/brand.json] [--out .design/brand]
//
// brand.json:
// { "name": "Keyring", "tagline": "…", "mark": "<svg …>…</svg>" | "path/to/mark.svg",
//   "wordmark": { "family": "Google Sans Flex", "weight": 600, "tracking": "-0.01em", "case": "none" },
//   "fonts": { "display": { "family": "…", "weight": 600 }, "text": { "family": "…", "weight": 400 }, "mono": { "family": "…" } },
//   "colors": { "paper": "#…", "ink": "#…", "accent": "#…", "accent-ink": "#…", … },   // names → roles (see lib/color.mjs)
//   "voice": { "is": ["…"], "not": ["…"] }, "og": { "headline": "…", "sub": "…" } }
// In the mark SVG use fill/stroke="currentColor" for ink parts and class="acc" for accent parts.
//
// Writes: board.jpg (look at this), og.png (1200×630), favicon.svg, mark-ink.svg, mark-light.svg, tokens.css.
// Prints the palette audit (awkward/AI-looking combinations, contrast).
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { launch } from './lib/pw.mjs';
import { googleLinks, familyName } from './lib/gfonts.mjs';
import { auditPalette, contrast, oklch } from './lib/color.mjs';
import { fontTier, isRound } from './lib/fonts.mjs';

const argv = process.argv.slice(2);
const src = argv.find(a => !a.startsWith('--') && argv[argv.indexOf(a) - 1] !== '--out') || '.design/brand.json';
const out = (() => { const i = argv.indexOf('--out'); return i < 0 ? path.join(path.dirname(src), 'brand') : argv[i + 1]; })();
const B = JSON.parse(readFileSync(src, 'utf8'));
mkdirSync(out, { recursive: true });
const mark = B.mark?.trim().startsWith('<svg') ? B.mark : existsSync(path.resolve(path.dirname(src), B.mark || '')) ? readFileSync(path.resolve(path.dirname(src), B.mark), 'utf8') : '';
const C = B.colors;
const pick = (re, fb) => Object.entries(C).find(([k]) => re.test(k))?.[1] || fb;
const paper = pick(/^(paper|bg|background|surface|canvas)$/, '#ffffff'), ink = pick(/^(ink|text|fg|foreground)$/, '#111111');
const accent = pick(/^(accent|brand|primary)$/, ink), accentInk = pick(/accent-ink|primary-ink|brand-ink/, accent);
const dark = pick(/^(night|dark|ink-bg|deep)$/, ink);
const F = B.fonts || {}, W = B.wordmark || {};
const fam = (f) => `'${familyName(f)}', ui-sans-serif, system-ui, sans-serif`;
const links = (await googleLinks([F.display?.family, F.text?.family, F.mono?.family, W.family])).map(h => `<link rel="stylesheet" href="${h}">`).join('');
const colorMark = (fg, acc) => mark.replace(/<svg/, `<svg style="color:${fg}"`).replace(/class="acc"/g, `class="acc" fill="${acc}" stroke="${acc}"`).replace(/(fill|stroke)="[^"]*"(?=[^>]*class="acc")/g, '');
const wm = (fg, acc, size = 44) => `<div class="lock" style="color:${fg}"><span class="mk" style="width:${size}px;height:${size}px">${colorMark(fg, acc)}</span><span class="wm" style="font-size:${size * 0.82}px">${B.name}</span></div>`;

// ---- assets
const markFor = (fg, acc) => colorMark(fg, acc).replace(/style="color:[^"]*"/, '').replace(/currentColor/g, fg);
writeFileSync(path.join(out, 'mark-ink.svg'), markFor(ink, accent));
writeFileSync(path.join(out, 'mark-light.svg'), markFor(paper, accent));
writeFileSync(path.join(out, 'favicon.svg'), markFor(ink, accent).replace(/<svg([^>]*)>/, `<svg$1><style>@media (prefers-color-scheme: dark){[fill="${ink}"]{fill:${paper}}[stroke="${ink}"]{stroke:${paper}}}</style>`));
writeFileSync(path.join(out, 'tokens.css'), `/* ${B.name} brand tokens — generated by brandboard.mjs */\n@import url("${(await googleLinks([F.display?.family, F.text?.family, F.mono?.family]))[0] || ''}");\n:root {\n${Object.entries(C).map(([k, v]) => `  --${k}: ${v};`).join('\n')}\n  --font-display: ${fam(F.display?.family || W.family)};\n  --font-text: ${fam(F.text?.family || F.display?.family)};${F.mono ? `\n  --font-mono: '${familyName(F.mono.family)}', ui-monospace, monospace;` : ''}\n}\n`);

// Tailwind v4 theme (import after tailwindcss): colours become bg-*/text-* utilities, fonts become font-display/font-text.
writeFileSync(path.join(out, 'tokens.tailwind.css'), `/* ${B.name} — Tailwind v4 theme, generated by brandboard.mjs */\n@theme {\n${Object.entries(C).map(([k, v]) => `  --color-${k}: ${v};`).join('\n')}\n  --font-display: ${fam(F.display?.family || W.family)};\n  --font-text: ${fam(F.text?.family || F.display?.family)};${F.mono ? `\n  --font-mono: '${familyName(F.mono.family)}', ui-monospace, monospace;` : ''}\n}\n`);

// ---- board
const sw = Object.entries(C).map(([k, v]) => { const o = oklch(v); return `<div class="sw"><i style="background:${v}"></i><b>${k}</b><span>${v}</span><span>L ${o.L.toFixed(2)} C ${o.C.toFixed(2)} H ${Math.round(o.H)}</span><span>on paper ${contrast(v, paper).toFixed(1)} · on ink ${contrast(v, ink).toFixed(1)}</span></div>`; }).join('');
const ladder = [72, 48, 32, 22, 17, 14].map((s, i) => `<div style="font:${i < 3 ? F.display?.weight || 600 : i === 3 ? 600 : F.text?.weight || 400} ${s}px/${i < 3 ? 1.08 : 1.45} ${fam(i < 4 ? F.display?.family || W.family : F.text?.family || F.display?.family)};letter-spacing:${i < 3 ? '-0.015em' : '0'}"><small>${s}</small> ${i < 3 ? (B.og?.headline || B.tagline || B.name) : B.tagline || 'The quick brown fox jumps over the lazy dog.'}</div>`).join('');
const og = `<div id="og" style="width:1200px;height:630px;background:${dark};color:${paper};display:flex;flex-direction:column;justify-content:space-between;padding:72px;box-sizing:border-box">
  ${wm(paper, accent, 56)}
  <div><div style="font:${F.display?.weight || 600} 76px/1.04 ${fam(F.display?.family || W.family)};letter-spacing:-0.02em;max-width:15em;text-wrap:balance">${B.og?.headline || B.tagline || ''}</div>
  ${B.og?.sub ? `<div style="font:400 28px/1.4 ${fam(F.text?.family || F.display?.family)};opacity:.78;margin-top:22px;max-width:36em">${B.og.sub}</div>` : ''}</div></div>`;
const html = `<!doctype html>${links}<style>
body{margin:0;background:#E9E8E4;font:14px/1.4 system-ui;color:#222}
.board{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:20px;width:1800px;box-sizing:border-box}
.cell{background:#fff;padding:22px;border-radius:6px;min-height:160px}.cell h3{margin:0 0 14px;font:600 12px system-ui;letter-spacing:.06em;text-transform:uppercase;color:#777}
.span2{grid-column:span 2}.span3{grid-column:span 3}
.lock{display:flex;align-items:center;gap:.45em}.mk{display:inline-flex}.mk svg{width:100%;height:100%}
.wm{font-family:${fam(W.family || F.display?.family)};font-weight:${W.weight || 600};font-variation-settings:${W.axes || 'normal'};letter-spacing:${W.tracking || '-0.01em'};text-transform:${W.case || 'none'};line-height:1}
.tiles{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.tile{border-radius:6px;padding:28px 20px;display:flex;align-items:center;justify-content:center;min-height:120px}
.sizes{display:flex;align-items:end;gap:26px}.sizes div{display:grid;justify-items:center;gap:6px;font-size:11px;color:#777}.sizes span svg{width:100%;height:100%}
.sws{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px}.sw{display:grid;gap:2px;font-size:11.5px}.sw i{height:64px;border-radius:5px;border:1px solid #0001}.sw span{color:#666}
.ladder>div{padding:6px 0;border-bottom:1px solid #eee;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:${ink}}.ladder small{font:11px system-ui;color:#999;display:inline-block;width:28px}
.voice{display:grid;grid-template-columns:1fr 1fr;gap:16px}.voice ul{margin:0;padding-left:18px}
.clear{display:inline-block;padding:22px;outline:1px dashed #d33;background:${paper}}
</style><div class="board">
<div class="cell span2"><h3>Lockups</h3><div class="tiles">
  <div class="tile" style="background:${paper}">${wm(ink, accent)}</div>
  <div class="tile" style="background:${dark}">${wm(paper, accent)}</div>
  <div class="tile" style="background:${accent}">${wm(contrast(ink, accent) > contrast(paper, accent) ? ink : paper, contrast(ink, accent) > contrast(paper, accent) ? ink : paper)}</div></div></div>
<div class="cell"><h3>Mark at size (favicon test)</h3><div class="sizes">${[96, 64, 32, 24, 16].map(s => `<div><span style="width:${s}px;height:${s}px;display:inline-flex;color:${ink}">${colorMark(ink, accent)}</span>${s}px</div>`).join('')}</div>
  <p style="color:#666;font-size:12px;margin-top:14px">Must still read at 16px. If it turns to mush, simplify the mark.</p>
  <div style="margin-top:10px"><span class="clear">${wm(ink, accent, 32)}</span> <span style="font-size:11px;color:#999">clear space ≈ mark height ÷ 1.5</span></div></div>
<div class="cell span3"><h3>Palette (OKLCH, contrast vs paper / ink)</h3><div class="sws">${sw}</div></div>
<div class="cell span2 ladder"><h3>Type — ${familyName(F.display?.family || W.family)}${F.text && F.text.family !== F.display?.family ? ' / ' + familyName(F.text.family) : ''}${F.mono ? ' / ' + familyName(F.mono.family) : ''}</h3>${ladder}</div>
<div class="cell"><h3>Voice</h3><div class="voice"><div><b>Is</b><ul>${(B.voice?.is || []).map(v => `<li>${v}</li>`).join('')}</ul></div><div><b>Is not</b><ul>${(B.voice?.not || []).map(v => `<li>${v}</li>`).join('')}</ul></div></div></div>
<div class="cell span3"><h3>Open Graph (1200×630, shown at 50%)</h3><div style="zoom:.5">${og}</div></div>
</div>`;
const tmp = path.join(out, 'board.html'); writeFileSync(tmp, html);
const b = await launch(); const p = await b.newPage({ viewport: { width: 1800, height: 1000 } });
await p.goto('file://' + path.resolve(tmp)); await p.evaluate(() => document.fonts.ready); await p.waitForTimeout(500);
await p.screenshot({ path: path.join(out, 'board.jpg'), type: 'jpeg', quality: 78, fullPage: true });
await p.setViewportSize({ width: 1200, height: 630 });
await p.setContent(`<!doctype html>${links}<style>body{margin:0}.lock{display:flex;align-items:center;gap:.45em}.mk{display:inline-flex}.mk svg{width:100%;height:100%}.wm{font-family:${fam(W.family || F.display?.family)};font-weight:${W.weight || 600};font-variation-settings:${W.axes || 'normal'};letter-spacing:${W.tracking || '-0.01em'};text-transform:${W.case || 'none'};line-height:1;font-variation-settings:${W.axes || 'normal'}}</style>${og}`);
await p.evaluate(() => document.fonts.ready); await p.waitForTimeout(300);
await p.locator('#og').screenshot({ path: path.join(out, 'og.png') });
await b.close();

// ---- report
const { findings } = auditPalette(Object.entries(C).map(([name, hex]) => ({ name, hex })));
const fontNotes = [...new Set([W.family, F.display?.family, F.text?.family].filter(Boolean).map(familyName))].map(f => `${f}${fontTier(f) ? ` [${fontTier(f)}]` : isRound(f) ? ' [round ✓]' : ''}`);
console.log(`brandboard → ${out}/board.jpg · og.png · favicon.svg · mark-ink.svg · mark-light.svg · tokens.css · tokens.tailwind.css`);
console.log(`fonts: ${fontNotes.join(', ')}`);
console.log(`accent-ink on paper ${contrast(accentInk, paper).toFixed(2)}:1 · ink on paper ${contrast(ink, paper).toFixed(2)}:1`);
for (const f of findings) console.log(`${['', 'LOW', 'MED', 'HIGH'][f.sev]} ${f.id}: ${f.msg}`);
if (!findings.length) console.log('palette: no awkward combinations found.');
